telegram_token: "6135042226:AAE2c91i58GPJc5TGkfnmXY7HJBd7quNwJU"
openai_api_key: "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"
use_chatgpt_api: true
allowed_telegram_usernames: [1430593323]  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
enable_message_streaming: true  # if set, messages will be shown to user word-by-word

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
